# Generated by Django 3.0.3 on 2020-02-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveSmallIntegerField(default=2000)),
                ('carb', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('protein', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('fat', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
        ),
    ]
